apiVersion: v1
kind: Config
clusters:
  - name: cluster
    cluster:
      server: {{ k8s_server }}
      certificate-authority-data: {{ k8s_ca_cert }}
users:
  - name: cluster
    user:
      token: {{ k8s_client_token }}
contexts:
  - name: cluster
    context:
      cluster: cluster
      name: cluster
      user: cluster
preferences: {}
current-context: cluster
